# .github/workflows/publish.yml
name: Publish package on npm & GitHub

on:
  push:
    tags:
      - "*.*.*"

jobs:
  test:
    uses: ./.github/workflows/test.yml

  github-release:
    runs-on: ubuntu-latest
    needs: [test]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: filename.js

  npm-publish:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}