# .github/workflows/test.yml
name: Run tests

on: [ push, pull_request, workflow_call ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci
      - run: npm test
